### ISSUE TITLE
Google Cloud , datas does not hit the CDN

### ISSUE THREAD

**Issue by kevinvenclovas** [versatiles-org/versatiles-documentation#22]
Hi,

unfortunately, this is not clearly described in the documentation. In my cloud service, I have activated the CDN. 
However, the tiles loaded via https://xxx/tiles/osm/14/8658/5633.pbf never reach the CDN, and the data is always delivered anew.

Maybe someone can spot an issue with my settings?

![image](https://github.com/versatiles-org/versatiles-documentation/assets/7681603/ba0ce4ec-dff3-4aa7-a12a-15dd0be2c9ac)

**Comment by MichaelKreil** [comment]
Did you found a solution?

**Comment by kevinvenclovas** [comment]
Yes, issue can be closed. I changed the CDN to cache all elements instead only the statics
