### ISSUE TITLE
docker run command not working

### ISSUE THREAD

**Issue by flatiron23** [versatiles-org/versatiles-documentation#9]
When I am trying to run the docker run command for versatiles/versatiles-frontend using the online map I always get the response:

```
error: unrecognized subcommand 'versatiles'

Usage: versatiles [OPTIONS] <COMMAND>
```
I am running Docker swarm on 4 Raspberry Pi 3 (ARM64). 
If you need any further information, I will provide them gladly.

Best regards

**Comment by MichaelKreil** [comment]
The docker files are here: https://github.com/versatiles-org/versatiles-docker/tree/main/docker
Did I miss something?

**Comment by flatiron23** [comment]
Many thanks at first for the repsonse. 
Maybe I just gave a bad description of the issue. Or I have completely misunderstood something.

In the [documentation](https://github.com/versatiles-org/versatiles-documentation/blob/main/guides/local_docker.md) in the section "Usage" is he following docker run command:
`docker run -p 8080:8080 versatiles/versatiles-frontend:latest-alpine \
  versatiles serve -s /frontend.br.tar -i 0.0.0.0 \
 '[osm]https://storage.googleapis.com/versatiles/download/planet/planet-20230605.versatiles'`

I assumed, that I can run this command for creating a corresponding container.
I have also tried it with versatiles/versatiles-frontend:latest-debian.
Download the images is working, but apparently it fails with above mentioned error message.

**Comment by MichaelKreil** [comment]
You are absolutely right.
The Docker documentation is completely out of date.
I'll update it right away.

**Comment by MichaelKreil** [comment]
This should work: https://github.com/versatiles-org/versatiles-documentation/blob/main/guides/local_docker.md

**Comment by MichaelKreil** [comment]
Unfortunately there were some problems with the Docker container, so I had to remove the ENTRYPOINT. 😕
I have already pushed new images and updated the documentation.
Sorry.

**Comment by flatiron23** [comment]
Hey, sorry for the late response.
I just wasn't able to check. Is it of for you, if I come back in the next two days?

**Comment by MichaelKreil** [comment]
No problem. :)

**Comment by flatiron23** [comment]
Works!
Excellent. Thank you very much for the quick response.
